project_id = "tgfpewbymloyxhpdfnzk"

[functions.razorpay-payment]
verify_jwt = false

[functions.razorpay-callback]
verify_jwt = false

[functions.phonepe-payment]
verify_jwt = false

[functions.phonepe-callback]
verify_jwt = false

[functions.phonepe-status]
verify_jwt = false

[functions.expire-pending-payments]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.supabase-proxy]
verify_jwt = false
